import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ weight: ["400", "600"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Enquiry Form',
  description: 'Generated by create next Js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
